{{- $root := .}}
{{- $fullName := include "talkstimer.fullname" . -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "talkstimer.name" . }}
    chart: {{ template "talkstimer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: talkstimer.com
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-www
  labels:
    app: {{ template "talkstimer.name" . }}
    chart: {{ template "talkstimer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: www.talkstimer.com
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: 80
{{- range $i, $e := until (.Values.replicaCount|int) }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $i }}
  labels:
    app: {{ template "talkstimer.name" $root }}
    chart: {{ template "talkstimer.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
{{- with $root.Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ $i }}.talkstimer.com
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-{{ $i }}
              servicePort: 80
{{- end }}
