---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  {{ template "talkstimer.fullname" . }}-mongodb
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany
  mountOptions: []
  nfs:
      path: /mnt/nfs/talkstimer-mongodb
      server: 10.244.0.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ template "talkstimer.fullname" . }}-mongodb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName:  {{ template "talkstimer.fullname" . }}-mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "talkstimer.fullname" . }}-mongodb
spec:
  selector:
    app: {{ template "talkstimer.fullname" . }}-mongodb
    chart: {{ template "talkstimer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "talkstimer.fullname" . }}-mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "talkstimer.fullname" . }}-mongodb
        chart: {{ template "talkstimer.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ template "talkstimer.fullname" . }}-mongodb
      containers:
        - name: mongodb
          imagePullPolicy: Always
          image: mongo:4-xenial
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ required "Missing mongodb.username" .Values.mongodb.username }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ required "Missing mongodb.password" .Values.mongodb.password }}
          volumeMounts:
            - name: datadir
              mountPath: /data/db
          ports:
            - containerPort: 27017
